headers = ["symboling", "normalized-losses", "make",  
           "fuel-type", "aspiration","num-of-doors", 
           "body-style","drive-wheels", "engine-location", 
           "wheel-base","length", "width","height", "curb-weight", 
           "engine-type","num-of-cylinders", "engine-size",  
           "fuel-system","bore","stroke", "compression-ratio", 
           "horsepower", "peak-rpm","city-mpg","highway-mpg","price"] 
           
car_names={
"alfa-romero":1,
"audi":2,
"bmw":3,
"chevrolet":4,
"dodge":5,
"honda":6,
"isuzu":7,
"jaguar":8,
"mazda":9,
"mercedes-benz":10,
"mercury":11,
"mitsubishi":12,
"nissan":13,
"peugot":14,
"plymouth":15,
"porsche":16,
"renault":17,
"saab":18,
"subaru":19,
"toyota":20,
"volkswagen":21,
"volvo":22
}
car_names_l=[
"alfa-romero",
"audi",
"bmw",
"chevrolet",
"dodge",
"honda",
"isuzu",
"jaguar",
"mazda",
"mercedes-benz",
"mercury",
"mitsubishi",
"nissan",
"peugot",
"plymouth",
"porsche",
"renault",
"saab",
"subaru",
"toyota",
"volkswagen",
"volvo"
]